### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by SiirRandall** [EvieePy/TwitchIO#4]
I been using my bot for a while now using your API. Everything if fine. But this is what happens when I try to run commands. It was working for a while and nothing has changed. 

```
Ignoring exception in ConnectionRefusedError:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/twitchio/base.py", line 205, in keep_alive
    await self.process_data(data)
  File "/home/pi/.local/lib/python3.5/site-packages/twitchio/base.py", line 255, in process_data
    await self.process_actions(data, _groupsdict, tags)
  File "/home/pi/.local/lib/python3.5/site-packages/twitchio/base.py", line 310, in process_actions
    await self.event_message(message)
  File "./tenebe.py", line 36, in event_message
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
```
Also love the API keep up the good work.

**Comment by SiirRandall** [comment]
Rewrote the bot and all is working again. Not sure why this failed. All is good again.
